### ISSUE TITLE
Allow both POST and GET for /portier/login

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-portier#5]
We have to build the redirect URL and it is not always trivial to do in the form, so in a lot of cases we are actually building a form in javascript before posting it. It would be easier to be able to do a get instead.

Plus it would be closed to the flow kinto-fxa provides.

**Comment by Natim** [comment]
Actually there are some security concern with sending private information in a get request.

https://blog.httpwatch.com/2009/02/20/how-secure-are-query-strings-over-https/

**Comment by n1k0** [comment]
If we do really want to be as secure as this post suggests, we should then probably cancel this patch and update kinto-fxa accordingly...

**Comment by Natim** [comment]
Well kinto-fxa is not sending any information with the first call :)

**Comment by n1k0** [comment]
Haha! Right!
